server:
  port: 3335
  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
  path: /var/log
  file: frontend.log
  level:
    org.slf4j: 'DEBUG'
    com.server: 'DEBUG'

provider:
  backend: http://localhost:3336/